server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://shopmanager.ch4egemc4efh.ap-southeast-2.rds.amazonaws.com:3306/shopmanager?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Vinh12111999
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1